//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public int id { get; set; }
        public Nullable<int> meeting_room_id { get; set; }
        public string host { get; set; }
        public Nullable<System.DateTime> time_from { get; set; }
        public Nullable<System.DateTime> time_to { get; set; }
    
        public virtual meeting_room meeting_room { get; set; }
    }
}
